// Offline flag asset generator — NOT run in the Worker.
// Rasterizes flag-icons SVGs, dithers to Spectra-6 (reusing the project's
// color image path), and writes src/worldcup-flags.ts as a committed base64 map.
//
// Run: npm run flags   (no API key needed)
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { Resvg } from "@resvg/resvg-js";

const BUILD = "/tmp/eink-dashboard-flags-build";
console.log("Compiling src -> " + BUILD + " ...");
execSync(`npx tsc -p tsconfig.test.json --outDir ${BUILD}`, { stdio: "inherit" });

const { ditherFloydSteinberg } = await import(path.join(BUILD, "src/dither-spectra6.js"));
const { encodePNGIndexed, pngToBase64 } = await import(path.join(BUILD, "src/png.js"));
const { SPECTRA6_PALETTE } = await import(path.join(BUILD, "src/spectra6.js"));

const W = 36; // raster width; height derived from 4:3 source (~27)

// FIFA TLA -> ISO-3166 alpha-2 (flag-icons key), for the exact 48 WC 2026 participants.
const MAP = {
  ALG: "dz", ARG: "ar", AUS: "au", AUT: "at", BEL: "be", BIH: "ba", BRA: "br",
  CAN: "ca", CIV: "ci", COD: "cd", COL: "co", CPV: "cv", CRO: "hr", CUW: "cw",
  CZE: "cz", ECU: "ec", EGY: "eg", ENG: "gb-eng", ESP: "es", FRA: "fr", GER: "de",
  GHA: "gh", HAI: "ht", IRN: "ir", IRQ: "iq", JOR: "jo", JPN: "jp", KOR: "kr",
  KSA: "sa", MAR: "ma", MEX: "mx", NED: "nl", NOR: "no", NZL: "nz", PAN: "pa",
  PAR: "py", POR: "pt", QAT: "qa", RSA: "za", SCO: "gb-sct", SEN: "sn", SUI: "ch",
  SWE: "se", TUN: "tn", TUR: "tr", URU: "uy", USA: "us", UZB: "uz",
};

const out = {};
let missing = 0;
for (const [tla, iso] of Object.entries(MAP)) {
  const svgPath = `node_modules/flag-icons/flags/4x3/${iso}.svg`;
  if (!existsSync(svgPath)) { console.warn("MISSING svg:", tla, "->", iso); missing++; continue; }
  const svg = readFileSync(svgPath, "utf8");
  const img = new Resvg(svg, { fitTo: { mode: "width", value: W } }).render();
  const rgba = img.pixels;
  const iw = img.width, ih = img.height;
  const rgb = new Uint8Array(iw * ih * 3);
  for (let i = 0, j = 0; i < rgba.length; i += 4, j += 3) {
    const a = rgba[i + 3] / 255; // composite over white
    rgb[j]     = Math.round(rgba[i]     * a + 255 * (1 - a));
    rgb[j + 1] = Math.round(rgba[i + 1] * a + 255 * (1 - a));
    rgb[j + 2] = Math.round(rgba[i + 2] * a + 255 * (1 - a));
  }
  const indices = ditherFloydSteinberg(rgb, iw, ih, SPECTRA6_PALETTE);
  const png = await encodePNGIndexed(indices, iw, ih, SPECTRA6_PALETTE);
  out[tla] = `${iw}x${ih}|` + pngToBase64(png);
}

const body = Object.keys(out).sort().map((k) => `  ${k}: ${JSON.stringify(out[k])},`).join("\n");
writeFileSync("src/worldcup-flags.ts",
`// GENERATED by scripts/generate-flags.mjs — do not edit by hand.
// FIFA TLA -> "WxH|<base64 indexed PNG>". Spectra-6 dithered offline from flag-icons.
export const FLAGS: Record<string, string> = {\n${body}\n};\n`);
console.log(`Wrote ${Object.keys(out).length} flags (${missing} missing) -> src/worldcup-flags.ts`);
